DROP TABLE IF EXISTS `dwd_tdzzsxt_xmsrmx`;
CREATE TABLE `dwd_tdzzsxt_xmsrmx`(
`xm_id` bigint NOT NULL  COMMENT '项目id',
`xm_bm` varchar(64)    COMMENT '项目编码',
`xm_mc` varchar(64)    COMMENT '项目名称',
`xm_dq_dm` varchar(6)    COMMENT '项目地区代码',
`ssswjg` varchar(100)    COMMENT '所属税务机关',
`nsrsbh` varchar(20)    COMMENT '纳税人识别号',
`nsrmc` varchar(300)    COMMENT '纳税人名称',
`qdtdsj` datetime    COMMENT '取得土地时间',
`jsfs` varchar(50)    COMMENT '结算方式',
`mjctzfs` varchar(50)    COMMENT '面积差调整方式',
`zzhtqdrq` varchar(50)    COMMENT '最早合同签订日期',
`sjpdbl` decimal(22,8)    COMMENT '售价偏低比例',
`jsyssz` varchar(100)    COMMENT '均价影响因素',
`jsysszmc` varchar(100)    COMMENT '均价影响因素名称',
`sjpdpjdj` decimal(22,8)    COMMENT '售价偏低平均单价',
`jsydghxkz_yd_mj` decimal(22,8)    COMMENT '用地面积',
`jsydghxkz_jz_gm` decimal(22,8)    COMMENT '建筑规模',
`ptzzjzmj` decimal(22,8)    COMMENT '普通住宅建筑面积',
`ptzzhtzj` decimal(22,8)    COMMENT '普通住宅合同总价',
`ptzzhtjzmj` decimal(22,8)    COMMENT '普通住宅合同建筑面积',
`rjlxx` decimal(22,8)    COMMENT '容积率下限',
`pzdtmjsx` decimal(22,8)    COMMENT '普宅单套面积上限',
`pzpjjyjgsx` decimal(22,8)    COMMENT '普宅平均交易价格上限',
`lh` varchar(64)    COMMENT '楼号',
`dy` varchar(64)    COMMENT '单元',
`lc` varchar(64)    COMMENT '楼层',
`fh` varchar(64) NOT NULL  COMMENT '房号',
`bw` varchar(64)    COMMENT '部位',
`cg` int(10) unsigned zerofill    COMMENT '层高',
`cjsc_jz_mj` decimal(22,8)    COMMENT '建筑面积(采集表_实测）',
`cjsc_tn_jz_mj` decimal(22,8)    COMMENT '套内建筑面积(采集表_实测）',
`cjsc_yt_jz_mj` decimal(22,8)    COMMENT '阳台建筑面积(采集表_实测）',
`cjsc_ft_jz_mj` decimal(22,8)    COMMENT '分摊的共有共用建筑面积(采集表_实测）',
`cjsc_fw_lx` varchar(10)    COMMENT '房屋类型(采集表_实测）',
`cjsc_fw_yt` varchar(10)    COMMENT '房屋用途(采集表_实测）',
`cjsc_fw_jg` char(1)    COMMENT '房屋结构(采集表_实测）',
`cjsc_sf_ks` char(1)    COMMENT '是否可售(采集表_实测）',
`shsc_jz_mj` decimal(22,8)    COMMENT '建筑面积(审核表_实测）',
`shsc_tn_jz_mj` decimal(22,8)    COMMENT '套内建筑面积(审核表_实测）',
`shsc_yt_jz_mj` decimal(22,8)    COMMENT '阳台建筑面积(审核表_实测）',
`shsc_ft_jz_mj` decimal(22,8)    COMMENT '分摊的共有共用建筑面积(审核表_实测）',
`shsc_ggptyjmj` decimal(22,8)    COMMENT '公共配套已移交面积(审核表_实测）',
`shsc_ggptwyjmj` decimal(22,8)    COMMENT '公共配套未移交面积(审核表_实测）',
`shsc_fw_lx` varchar(10)    COMMENT '房屋类型(审核表_实测）',
`shsc_fw_yt` varchar(10)    COMMENT '房屋用途(审核表_实测）',
`shsc_fw_jg` char(1)    COMMENT '房屋结构(审核表_实测）',
`fp_se` decimal(22,8)    COMMENT '税额',
`fp_je` decimal(22,8)    COMMENT '发票金额（不含税）',
`fp_bzsje` decimal(22,8)    COMMENT '不征税金额',
`sfglf` varchar(1)    COMMENT '购房人是否是关联方（Y:是；N:否）',
`ybdwgx` varchar(64)    COMMENT '与本单位关系',
`cj_shfkje` decimal(22,8)    COMMENT '实收房款款金额',
`cjxs_gfr` varchar(128)    COMMENT '购房人(采集表_销售明细）',
`cjxs_ht_qd_rq` datetime    COMMENT '合同签订日期(采集表_销售明细）',
`cjxs_ht_zj` decimal(22,8)    COMMENT '合同总价（含税）      (采集表_销售明细）',
`cjxs_ht_jz_mj` decimal(22,8)    COMMENT '合同建筑面积(采集表_销售明细）',
`cjxs_ht_tn_mj` decimal(22,8)    COMMENT '合同套内面积(采集表_销售明细）',
`cjxs_ht_jz_dj` decimal(22,8)    COMMENT '合同建筑单价（含税）(采集表_销售明细）',
`cjxs_ht_tn_dj` decimal(22,8)    COMMENT '合同套内单价（含税）(采集表_销售明细）',
`cjxs_ds_fy` decimal(22,8)    COMMENT '计入房款的代收费用(采集表_销售明细）',
`cjxs_js_zj_hs` decimal(22,8)    COMMENT '结算信息--结算总价（含税）(采集表_销售明细）',
`cjxs_js_zj_bhs` decimal(22,8)    COMMENT '结算信息--结算总价（不含税）(采集表_销售明细）',
`cjxs_yys_xssr` decimal(22,8)    COMMENT '结算信息--营业税销售收入(采集表_销售明细）',
`cjxs_zzs_xssr` decimal(22,8)    COMMENT '结算信息--增值税销售收入（不含税）(采集表_销售明细）',
`cjxs_qy_sbdj` decimal(22,8)    COMMENT '计税信息--企业申报单价（含税）(采集表_销售明细）',
`cjxs_qy_sbmj` decimal(22,8)    COMMENT '计税信息--企业申报面积(采集表_销售明细）',
`cjxs_qy_sbsr_hs` decimal(22,8)    COMMENT '计税信息--企业申报收入（含税）(采集表_销售明细）',
`cjxs_qy_sbsr_bhs` decimal(22,8)    COMMENT '计税信息--企业申报收入（不含税）(采集表_销售明细）',
`cjxs_xs_fw_lx` varchar(10)    COMMENT '房屋类型(采集表_销售明细）',
`cjxs_xs_fw_yt` varchar(10)    COMMENT '房屋用途(采集表_销售明细）',
`cjxs_jf_bz` char(1)    COMMENT '交房标准(采集表_销售明细）',
`cjxs_cx` char(1)    COMMENT '朝向(采集表_销售明细）',
`cjxs_jf_rq` datetime    COMMENT '房屋交付日期(采集表_销售明细）',
`cjxs_zr_lx` char(1)    COMMENT '转让类型(采集表_销售明细）',
`shxs_ht_zj` decimal(22,8)    COMMENT '合同总价（含税）(审核表_销售明细）',
`shxs_ht_jz_mj` decimal(22,8)    COMMENT '合同建筑面积(审核表_销售明细）',
`shxs_ht_tn_mj` decimal(22,8)    COMMENT '合同套内面积(审核表_销售明细）',
`shxs_zr_lx` char(1)    COMMENT '转让类型(审核表_销售明细）',
`shxs_jf_bz` char(1)    COMMENT '交房标准（审核表_销售明细)',
`shxs_cx` char(1)    COMMENT '朝向（审核表_销售明细)',
`sh_shfkje` decimal(22,8)    COMMENT '实收房款金额(审核表_实收房款金额）',
`update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据更新时间',
PRIMARY KEY (`xm_id`,`fh`)
) COMMENT='土地增值税项目收入明细';

DROP TABLE IF EXISTS `dwd_tdzzsxt_xmhzxx`;
CREATE TABLE `dwd_tdzzsxt_xmhzxx`(
`xm_id` bigint NOT NULL  COMMENT '项目id',
`xm_bm` varchar(64)    COMMENT '项目编码',
`xm_mc` varchar(64)    COMMENT '项目名称',
`xm_dq_dm` varchar(6)    COMMENT '项目地区代码',
`ssswjg` varchar(100)    COMMENT '所属税务机关',
`nsrsbh` varchar(20)    COMMENT '纳税人识别号',
`nsrmc` varchar(300)    COMMENT '纳税人名称',
`qdtdsj` datetime    COMMENT '取得土地时间',
`jsfs` varchar(50)    COMMENT '结算方式',
`mjctzfs` varchar(50)    COMMENT '面积差调整方式',
`jsydghxkz_yd_mj` decimal(22,8)    COMMENT '用地面积',
`jsydghxkz_jz_gm` decimal(22,8)    COMMENT '建筑规模',
`ptzzjzmj` decimal(22,8)    COMMENT '普通住宅建筑面积',
`ptzzhtzj` decimal(22,8)    COMMENT '普通住宅合同总价',
`ptzzhtjzmj` decimal(22,8)    COMMENT '普通住宅合同建筑面积',
`rjlxx` decimal(22,8)    COMMENT '容积率下限',
`pzdtmjsx` decimal(22,8)    COMMENT '普宅单套面积上限',
`pzpjjyjgsx` decimal(22,8)    COMMENT '普宅平均交易价格上限',
`tdsyqqysbmj_lxpf` decimal(22,8)    COMMENT '土地使用权企业上报面积_立项批复',
`tdsyqqysbmj_gytdsyqz` decimal(22,8)    COMMENT '土地使用权企业上报面积_国有土地使用权证',
`tdsyqqysbmj_gytdsyq_crht` decimal(22,8)    COMMENT '土地使用权企业上报面积_国有土地使用权出（受）让合同',
`tdsyqqysbmj_jsydghxkz` decimal(22,8)    COMMENT '土地使用权企业上报面积_建设用地规划许可证',
`zjzmjshmj_jsgcghxkz` decimal(22,8)    COMMENT '总建筑面积审核面积合计_建设工程规划许可证',
`qsmx_zjz_mj` decimal(22,8)    COMMENT '总建筑面积(清算明细)',
`qsmx_ks_jz_mj` decimal(22,8)    COMMENT '可售建筑面积(清算明细)',
`qsmx_ys_jz_mj` decimal(22,8)    COMMENT '已售建筑面积(清算明细)',
`qsmx_ws_jz_mj` decimal(22,8)    COMMENT '未售建筑面积(清算明细)',
`qsmx_cz_zy_jz_mj` decimal(22,8)    COMMENT '其中：出租或自用建筑面积(清算明细)',
`qsmx_ds_jz_mj` decimal(22,8)    COMMENT '其中：待售建筑面积(清算明细)',
`qsmx_yxkc_gg_mj` decimal(22,8)    COMMENT '不可售建筑面积--允许扣除的公共配套设施等面积(清算明细)',
`qsmx_byxkc_mj` decimal(22,8)    COMMENT '不可售建筑面积--不允许扣除的面积(清算明细)',
`cjsc_jz_mj` decimal(22,8)    COMMENT '建筑面积(采集表_实测）',
`cjsc_tn_jz_mj` decimal(22,8)    COMMENT '套内建筑面积(采集表_实测）',
`cjsc_yt_jz_mj` decimal(22,8)    COMMENT '阳台建筑面积(采集表_实测）',
`cjsc_ft_jz_mj` decimal(22,8)    COMMENT '分摊的共有共用建筑面积(采集表_实测）',
`cjsc_ks_jz_mj` decimal(22,8)    COMMENT '可售建筑面积(实测)',
`cjxs_ht_zj` decimal(22,8)    COMMENT '合同总价（含税）      (采集表_销售明细）',
`cjxs_ht_jz_mj` decimal(22,8)    COMMENT '合同建筑面积(采集表_销售明细）',
`cjxs_ht_tn_mj` decimal(22,8)    COMMENT '合同套内面积(采集表_销售明细）',
`cjxs_ht_jz_dj` decimal(22,8)    COMMENT '合同建筑单价（含税）(采集表_销售明细）',
`cjxs_ht_tn_dj` decimal(22,8)    COMMENT '合同套内单价（含税）(采集表_销售明细）',
`cjxs_ds_fy` decimal(22,8)    COMMENT '计入房款的代收费用(采集表_销售明细）',
`cjxs_js_zj_hs` decimal(22,8)    COMMENT '结算信息--结算总价（含税）(采集表_销售明细）',
`cjxs_js_zj_bhs` decimal(22,8)    COMMENT '结算信息--结算总价（不含税）(采集表_销售明细）',
`cjxs_yys_xssr` decimal(22,8)    COMMENT '结算信息--营业税销售收入(采集表_销售明细）',
`cjxs_zzs_xssr` decimal(22,8)    COMMENT '结算信息--增值税销售收入（不含税）(采集表_销售明细）',
`cjxs_qy_sbdj` decimal(22,8)    COMMENT '计税信息--企业申报单价（含税）(采集表_销售明细）',
`cjxs_qy_sbmj` decimal(22,8)    COMMENT '计税信息--企业申报面积(采集表_销售明细）',
`cjxs_qy_sbsr_hs` decimal(22,8)    COMMENT '计税信息--企业申报收入（含税）(采集表_销售明细）',
`cjxs_qy_sbsr_bhs` decimal(22,8)    COMMENT '计税信息--企业申报收入（不含税）(采集表_销售明细）',
`shsc_jz_mj` decimal(22,8)    COMMENT '建筑面积(审核表_实测）',
`shsc_tn_jz_mj` decimal(22,8)    COMMENT '套内建筑面积(审核表_实测）',
`shsc_yt_jz_mj` decimal(22,8)    COMMENT '阳台建筑面积(审核表_实测）',
`shsc_ft_jz_mj` decimal(22,8)    COMMENT '分摊的共有共用建筑面积(审核表_实测）',
`shsc_ggptyjmj` decimal(22,8)    COMMENT '公共配套已移交面积(审核表_实测）',
`shsc_ggptwyjmj` decimal(22,8)    COMMENT '公共配套未移交面积(审核表_实测）',
`shxs_ht_zj` decimal(22,8)    COMMENT '合同总价（含税）(审核表_销售明细）',
`shxs_ht_jz_mj` decimal(22,8)    COMMENT '合同建筑面积(审核表_销售明细）',
`shxs_ht_tn_mj` decimal(22,8)    COMMENT '合同套内面积(审核表_销售明细）',
`sh_shfkje` decimal(22,8)    COMMENT '实收房款金额(审核表_实收房款金额）',
`fp_yyskpje` decimal(22,8)    COMMENT '营业税开票金额合计（发票）',
`yysse` decimal(22,8)    COMMENT '营业税税额',
`update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据更新时间',
PRIMARY KEY (`xm_id`)
) COMMENT='土地增值税项目汇总信息 ';

